version: 0.2

env:
  variables:
    AWS_REGION: "ap-northeast-1"
    ACCOUNT_ID: "654654329506"
    ECR_REPO: "labola-booking-prod"
    LAMBDA_FUNCTION_NAME: "labola-booking-lambda"

phases:
  pre_build:
    commands:
      - "set -eu"
      - "echo === Tool versions ==="
      - "aws --version"
      - "docker --version"
      - "echo === Login to ECR ==="
      - "ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - "IMAGE_URI=${ECR_URI}/${ECR_REPO}:latest"
      - "aws ecr get-login-password --region ${AWS_REGION} > /tmp/ecr_pass"
      - "cat /tmp/ecr_pass | docker login --username AWS --password-stdin ${ECR_URI}"

  build:
    commands:
      - "set -eu"
      - "echo === Docker build ==="
      - "docker build -t ${ECR_REPO}:latest ."
      - "docker tag ${ECR_REPO}:latest ${IMAGE_URI}"

  post_build:
    commands:
      - "set -eu"
      - 'if [ "${CODEBUILD_BUILD_SUCCEEDING:-0}" != "1" ]; then echo "Build failed, skip push/update"; exit 1; fi'
      - "echo === Push to ECR ==="
      - "docker push ${IMAGE_URI}"
      - "echo === Update Lambda image ==="
      - "aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --image-uri ${IMAGE_URI}"
      - "echo Done: ${IMAGE_URI}"
