version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    ECR_REPO: labola-booking-prod
    LAMBDA_FUNCTION_NAME: labola-booking-lambda
    ACCOUNT_ID: "654654329506"

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - echo "Login to ECR..."
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}
      - IMAGE_URI=${ECR_URI}/${ECR_REPO}:latest
      - echo "IMAGE_URI=${IMAGE_URI}"

  build:
    commands:
      - echo "Docker build..."
      - docker build -t ${ECR_REPO}:latest .
      - docker tag ${ECR_REPO}:latest ${IMAGE_URI}

  post_build:
    commands:
      - echo "Push to ECR..."
      - docker push ${IMAGE_URI}
      - echo "Update Lambda to the latest image..."
      - aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --image-uri ${IMAGE_URI}
      - echo "Done."

# artifactsは不要（今回はコンテナをECRにpushするだけ）
